"""Add dyslexia tests and remedials schema

Revision ID: 21bad4da2995
Revises: 
Create Date: 2025-09-18 18:06:53.934426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bad4da2995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('g2k_learning_difficulties')
        batch_op.drop_column('g2k_educational_background')
        batch_op.drop_column('g2k_previous_assessments')
        batch_op.drop_column('g2k_goals')
        batch_op.drop_column('g2k_support_services')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g2k_support_services', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('g2k_goals', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('g2k_previous_assessments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('g2k_educational_background', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('g2k_learning_difficulties', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
